<?php

namespace Videoclub\Clases\Soportes;

use Clases\Soportes\Soporte;

class Dvd extends Soporte
{
    public array $idiomas;
    private string $formatPantalla;
    public function __construct(string $titulo, int $numero,array $idiomas, string $formatPantalla = '1980px x 1600px', float $precio = 5)
    {
        parent::__construct($titulo, $numero, $precio);
        $this->idiomas = $idiomas;
        $this->formatPantalla = $formatPantalla;
    }

    public function muestraResumen()
    {
        parent::muestraResumen(); // TODO: Change the autogenerated stub
        echo ", el formato de pantalla és : $this->formatPantalla y los idiomas son los siguientes:";
        foreach ($this->idiomas as $idioma){
            echo "<br />- $idioma";
        }
    }
}