<?php

namespace Clases\Soportes;

use Clases\Soportes\Soporte;

class Juego extends Soporte
{
    public string $consola;
    private int $minNumJugadores;
    private int $maxNumJugadores;

    public function __construct(string $titulo, int $numero, string $consola, float $precio = 5,
                                int $minNumJugadores = 1, int $maxNumJugadores = 2)
    {
        parent::__construct($titulo, $numero, $precio);
        $this->consola = $consola;
        $this->minNumJugadores = $minNumJugadores;
        $this->maxNumJugadores = $maxNumJugadores;

    }

    public function muestraJugadoresPosibles():string{
        return ", se puede jugar de $this->minNumJugadores a $this->maxNumJugadores jugadores";
    }

    public function muestraResumen()
    {
        parent::muestraResumen(); // TODO: Change the autogenerated stub
        echo $this->muestraJugadoresPosibles();
        echo " y esta disponible para la $this->consola";
    }
}