<?php

namespace videoclub;

use videoclub\Soporte;

class CintaVideo extends Soporte
{
    private int $duracion;

    public function __construct(string $titulo, int $numero, int $duracion,  float $precio = 5)
    {
        parent::__construct($titulo, $numero, $precio);
        $this->duracion = $duracion;
    }

    public function muestraResumen()
    {
        parent::muestraResumen(); // TODO: Change the autogenerated stub
        echo " y la duración es: $this->duracion";
    }
}

